# Generated by Django 4.0.2 on 2022-02-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_for_bot_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_bot',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Имя'),
        ),
    ]
