# Generated by Django 4.0.2 on 2022-03-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_city_options_alter_for_bot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='for_bot',
            name='inf',
        ),
    ]
